"""Typed data models shared across the tool pipeline.

These pydantic models are the contract between the tools in
``legal_agent.agent.tools``. Keep parsing, segmentation, citation and report
assembly deterministic; only clause judgement (``analyze_clause``) and prose
generation should ever involve the model.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# The disclaimer is a product requirement (SPEC §0). Every substantive output
# must carry it. It lives here so it cannot be skipped by report assembly.
# ---------------------------------------------------------------------------
DISCLAIMER = (
    "This analysis is informational only. It is generated by software and may "
    "be incomplete or wrong. It is NOT legal advice and does not create an "
    "attorney-client relationship. Contract law and enforceability vary by "
    "jurisdiction. Review these findings with a qualified lawyer licensed in "
    "the relevant jurisdiction before relying on them or taking action."
)


class Severity(str, Enum):
    """How serious a finding is for the analysed party."""

    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

    @property
    def rank(self) -> int:
        return _SEVERITY_ORDER[self]


_SEVERITY_ORDER = {
    Severity.INFO: 0,
    Severity.LOW: 1,
    Severity.MEDIUM: 2,
    Severity.HIGH: 3,
    Severity.CRITICAL: 4,
}


class Confidence(str, Enum):
    """Calibrated confidence in a finding. Never manufacture false certainty."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class CharSpan(BaseModel):
    """Character offsets into the normalized document text (end exclusive)."""

    start: int = Field(..., ge=0)
    end: int = Field(..., ge=0)

    def slice(self, text: str) -> str:
        return text[self.start : self.end]


class Document(BaseModel):
    """A parsed contract: normalized text plus enough metadata to cite it."""

    path: str
    text: str
    source_format: str  # "pdf" | "docx" | "txt"
    page_count: int = 1
    # Character offset of the start of each page in ``text`` (page 1 -> 0).
    page_starts: list[int] = Field(default_factory=lambda: [0])
    title: str | None = None
    detected_parties: list[str] = Field(default_factory=list)

    def page_for_offset(self, offset: int) -> int:
        """1-indexed page number containing ``offset``."""
        page = 1
        for i, start in enumerate(self.page_starts):
            if offset >= start:
                page = i + 1
            else:
                break
        return page


class Clause(BaseModel):
    """A segmented clause/section with a stable reference and citation span."""

    id: str
    heading: str | None
    text: str
    char_span: CharSpan
    page: int = 1


class Finding(BaseModel):
    """A flagged risk in a clause, with reasoning and a proposed redline."""

    risk_type: str
    severity: Severity
    rationale: str
    clause_id: str
    citation: str  # quoted contract text supporting the finding
    suggested_redline: str
    confidence: Confidence


class Report(BaseModel):
    """The assembled, sorted risk report (machine-readable half)."""

    document_path: str
    document_title: str | None
    perspective: str
    jurisdiction: str | None
    findings: list[Finding]
    clause_count: int
    executive_summary: str
    disclaimer: str = DISCLAIMER

    def severity_counts(self) -> dict[str, int]:
        counts = {s.value: 0 for s in Severity}
        for f in self.findings:
            counts[f.severity.value] += 1
        return counts
